---
# Deploy all configs to all vms
#execute verbose to view more:: 
#ansible-playbook vm_playbook.yaml -vvvv -u root
#execute verbose to view more:: use tags for specific stuffs in playbook
#ansible-playbook vm_playbook.yaml -vvvv -u root

# - hosts: all
#   roles:
#   - role: common

- hosts: RHEL
  gather_facts: yes
  remote_user: root
  roles:
  - role: RHEL

- hosts: Debian
  gather_facts: "{{ gather_facts }}"
  remote_user: "{{ remote_user }}"
  roles:
  - role: Debian