---
# Handler for Redhat VMs

- name: restart iptables
  service: name=iptables state=restarted

- name: restart httpd
  service: name=httpd state=restarted

- name: restart mysqld
  service: name=mysqld state=restarted

#autostart service use systemctl enable OR chkconfig
# - name: add mysqld to initd
#   shell: /sbin/chkconfig --level 345 mysqld on
- name: autostart mysqld
  shell: /usr/bin/systemctl enable mysqld.service